/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package in_frames;

import Connection.jdbc;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class In_payments extends javax.swing.JInternalFrame {

    jdbc cdb = new jdbc();

    public In_payments() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layer_payment = new javax.swing.JLayeredPane();
        l_totalfee = new javax.swing.JLabel();
        l_totalfeecents = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        t_sno1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        t_sname1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        t_snic1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        labelDue = new javax.swing.JLabel();
        t_due = new javax.swing.JTextField();
        bfinish = new javax.swing.JButton();
        t_fee = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        combo_month = new javax.swing.JComboBox();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Payments");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img$icon/site_icon.png"))); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l_totalfee.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l_totalfee.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_totalfee.setText("0");
        l_totalfee.setBounds(177, 180, 80, 30);
        layer_payment.add(l_totalfee, javax.swing.JLayeredPane.DEFAULT_LAYER);

        l_totalfeecents.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l_totalfeecents.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_totalfeecents.setText(".00");
        l_totalfeecents.setBounds(250, 180, 30, 30);
        layer_payment.add(l_totalfeecents, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Total class fee :");
        jLabel2.setBounds(10, 190, 140, 18);
        layer_payment.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Student No :");
        jLabel23.setMaximumSize(new java.awt.Dimension(100, 19));
        jLabel23.setMinimumSize(new java.awt.Dimension(100, 19));
        jLabel23.setPreferredSize(new java.awt.Dimension(100, 19));
        jLabel23.setBounds(10, 70, 140, 19);
        layer_payment.add(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);

        t_sno1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        t_sno1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_sno1.setEnabled(false);
        t_sno1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_sno1FocusLost(evt);
            }
        });
        t_sno1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_sno1KeyPressed(evt);
            }
        });
        t_sno1.setBounds(170, 60, 270, 27);
        layer_payment.add(t_sno1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Name :");
        jLabel24.setMaximumSize(new java.awt.Dimension(100, 19));
        jLabel24.setMinimumSize(new java.awt.Dimension(100, 19));
        jLabel24.setPreferredSize(new java.awt.Dimension(100, 19));
        jLabel24.setBounds(10, 110, 140, 19);
        layer_payment.add(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);

        t_sname1.setEditable(false);
        t_sname1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        t_sname1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_sname1.setBounds(170, 100, 270, 24);
        layer_payment.add(t_sname1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("N.I.C  No :");
        jLabel27.setMaximumSize(new java.awt.Dimension(100, 19));
        jLabel27.setMinimumSize(new java.awt.Dimension(100, 19));
        jLabel27.setPreferredSize(new java.awt.Dimension(100, 19));
        jLabel27.setBounds(10, 150, 140, 19);
        layer_payment.add(jLabel27, javax.swing.JLayeredPane.DEFAULT_LAYER);

        t_snic1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        t_snic1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_snic1.setEnabled(false);
        t_snic1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_snic1FocusLost(evt);
            }
        });
        t_snic1.setBounds(170, 140, 170, 24);
        layer_payment.add(t_snic1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("v");
        jLabel28.setBounds(340, 140, 30, 20);
        layer_payment.add(jLabel28, javax.swing.JLayeredPane.DEFAULT_LAYER);

        labelDue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelDue.setBounds(180, 290, 260, 30);
        layer_payment.add(labelDue, javax.swing.JLayeredPane.DEFAULT_LAYER);

        t_due.setEditable(false);
        t_due.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        t_due.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_due.setText("0.00");
        t_due.setBounds(170, 260, 270, 35);
        layer_payment.add(t_due, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bfinish.setFont(new java.awt.Font("Centaur", 1, 24)); // NOI18N
        bfinish.setText("Finish");
        bfinish.setEnabled(false);
        bfinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfinishActionPerformed(evt);
            }
        });
        bfinish.setBounds(520, 260, 220, 40);
        layer_payment.add(bfinish, javax.swing.JLayeredPane.DEFAULT_LAYER);

        t_fee.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        t_fee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_fee.setText("0.00");
        t_fee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_feeFocusGained(evt);
            }
        });
        t_fee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_feeKeyPressed(evt);
            }
        });
        t_fee.setBounds(170, 220, 270, 35);
        layer_payment.add(t_fee, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("A Fee Of :");
        jLabel30.setBounds(10, 230, 140, 18);
        layer_payment.add(jLabel30, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("For Month :");
        jLabel5.setBounds(10, 20, 140, 30);
        layer_payment.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        combo_month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        combo_month.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_monthItemStateChanged(evt);
            }
        });
        combo_month.setBounds(170, 20, 200, 30);
        layer_payment.add(combo_month, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel31.setText("Total Due Payment :");
        jLabel31.setBounds(10, 270, 140, 14);
        layer_payment.add(jLabel31, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel32.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img$icon/LB4.png"))); // NOI18N
        jLabel32.setEnabled(false);
        jLabel32.setBounds(-80, 0, 840, 550);
        layer_payment.add(jLabel32, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(layer_payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 757, 321));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_sno1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_sno1FocusLost
        ResultSet r = null;
        try {
            r = cdb.getdata("select * from students2 where stu_no='" + t_sno1.getText() + "'");
            if (r.first()) {
                t_sname1.setText(r.getString("name"));
                t_snic1.setText(r.getString("nic"));
            }

        } catch (Exception e) {
            System.out.println(e);
        } finally {
            try {
                if (r != null) {
                    r.close();
                }
            } catch (SQLException e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_t_sno1FocusLost

    private void t_snic1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_snic1FocusLost
        ResultSet r = null;
        if (t_sno1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(layer_payment, "Enter Student number to continue");
        } else {
            try {
                int i = 0;
//                int fee = Integer.parseInt(l_totalfee.getText());
//                String sub = String.valueOf(fee + 1200);

                r = cdb.getdata("select * from students2 where stu_no='" + t_sno1.getText() + "'");
                if (r.next()) {
                    t_sname1.setText(r.getString("name"));
                    t_snic1.setText(r.getString("nic"));
                    if (!r.getString("subj1").isEmpty()) {
                        //   l_totalfee.setText(sub);
                        i++;
                    }
                    if (!r.getString("subj2").isEmpty()) {
                        // l_totalfee.setText(sub);
                        i++;
                    }
                    if (!r.getString("subj3").isEmpty()) {
                        //  l_totalfee.setText(sub);
                        i++;
                    }
                    l_totalfee.setText(Integer.toString(i * 1200));
                }
            } catch (Exception e) {
                System.out.println(e);
            } finally {
                try {
                    if (r != null) {
                        r.close();
                    }
                } catch (SQLException e) {
                    System.out.println(e);
                }
            }
        }
    }//GEN-LAST:event_t_snic1FocusLost

    private void bfinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfinishActionPerformed
        try {
            Connection.jdbc.con().createStatement()
                    .executeUpdate("insert into payments(stu_no,nic,total_fee,paid,due,month)"
                    + "values('" + t_sno1.getText() + "','" + t_snic1.getText() + "',"
                    + " '" + l_totalfee.getText() + "','" + t_fee.getText() + "','" + t_due.getText() + "',"
                    + " '" + combo_month.getSelectedItem().toString() + "')");
            System.out.println("payment success");
            JOptionPane.showMessageDialog(null, "Payment Successfull!",
                    "Success..", JOptionPane.INFORMATION_MESSAGE);
            resetFields();
        } catch (Exception e) {
            System.out.println(e);
        }
        System.gc();
    }//GEN-LAST:event_bfinishActionPerformed

    private void t_sno1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_sno1KeyPressed
        ResultSet r2 = null, r = null;
        if (evt.getKeyChar() == 10) {
            if (t_sno1.getText().isEmpty()) {
                JOptionPane.showMessageDialog(layer_payment, "Enter Student number to continue");
            } else {
                try {
                    int i = 0;
//                int fee = Integer.parseInt(l_totalfee.getText());
//                String sub = String.valueOf(fee + 1200);

                    r = cdb.getdata("select * from students2 where stu_no='" + t_sno1.getText() + "'");
                    r.next();
                    t_sname1.setText(r.getString("name"));
                    t_snic1.setText(r.getString("nic"));

                    if (!r.getString("subj1").isEmpty()) {
                        //   l_totalfee.setText(sub);
                        i++;
                    }
                    if (!r.getString("subj2").isEmpty()) {
                        // l_totalfee.setText(sub);
                        i++;
                    }
                    if (!r.getString("subj3").isEmpty()) {
                        //  l_totalfee.setText(sub);
                        i++;
                    }
                    l_totalfee.setText(Integer.toString(i * 1200));



                    //----------(BELOW) loading previous payments to form if has been submitted for that month

                    r2 = jdbc.con().createStatement().executeQuery("select * from payments "
                            + "where stu_no='" + t_sno1.getText() + "' and month='" + combo_month.getSelectedItem().toString() + "'");
                    if (r2.first()) {
                        l_totalfee.setText(r2.getString("total_fee").toString());
                        t_due.setText(r2.getString("due" + ".00"));
                    }
                } catch (Exception e) {
                    System.out.println("error loading due of month" + e);
                } finally {
                    try {
                        if (r != null) {
                            r.close();
                        }if(r2!=null){
                            r2.close();
                        }
                    } catch (SQLException e) {
                        System.out.println(e);
                    }
                }
            }
        }
    }//GEN-LAST:event_t_sno1KeyPressed

    private void t_feeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_feeKeyPressed
        if (evt.getKeyCode() >= 46 && evt.getKeyCode() <= 57 | evt.getKeyCode() == 8
                | evt.getKeyCode() == 127) {

            t_fee.setEditable(true);

        } else if (evt.getKeyCode() == 10) {
            if (t_due.getText().isEmpty()) {//------------empty due field makes a new payment for the month,
                //---------if student has paid previously for the month, it's processed below
                int total = Integer.valueOf(l_totalfee.getText()); //class fee
                int fee = Integer.valueOf(t_fee.getText()); // given money
                int due = total - fee;
                int negDue = fee - total;
                if (due < 0) {
                    t_due.setText(String.valueOf(negDue));
                    t_fee.setText(t_fee.getText() + ".00");
                    labelDue.setText("<html><font color=red>To Student</font><html>");
                    combo_month.setEnabled(true);
                    bfinish.setEnabled(true);
                    bfinish.grabFocus();
                } else if (due > 0) {
                    t_due.setText(String.valueOf(due) + ".00");
                    t_fee.setText(t_fee.getText() + ".00");
                    labelDue.setText("<html><font color=red>From Student</font><html>");
                    combo_month.setEnabled(true);
                    bfinish.setEnabled(true);
                    bfinish.grabFocus();
                }
            } else if (!t_due.getText().isEmpty()) { //---------if student has paid previously for the month, it's processed here
                int duedue = Integer.valueOf(t_due.getText()) - Integer.valueOf(t_fee.getText());
                int negduedue = Integer.valueOf(t_fee.getText()) - Integer.valueOf(t_due.getText());

                if (duedue < 0) {
                    t_due.setText(String.valueOf(negduedue));
                    t_fee.setText(t_fee.getText() + ".00");
                    labelDue.setText("<html><font color=red>To Student</font><html>");
                    combo_month.setEnabled(true);
                    bfinish.setEnabled(true);
                    bfinish.grabFocus();
                } else if (duedue > 0) {
                    t_due.setText(String.valueOf(duedue) + ".00");
                    t_fee.setText(t_fee.getText() + ".00");
                    labelDue.setText("<html><font color=red>From Student</font><html>");
                    combo_month.setEnabled(true);
                    bfinish.setEnabled(true);
                    bfinish.grabFocus();
                }
            }

        } else {
            t_fee.setEditable(false);
            JOptionPane.showMessageDialog(layer_payment, "Enter a numeric cash value !");
            t_fee.setText("");
            t_fee.grabFocus();
        }
        // System.out.println(evt.getKeyCode());
    }//GEN-LAST:event_t_feeKeyPressed

    private void t_feeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_feeFocusGained
        if (t_due.getText().isEmpty()) {
            t_fee.setText("");
        } else {
            t_fee.setText("");
            t_due.setText("");
        }
    }//GEN-LAST:event_t_feeFocusGained

    private void combo_monthItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_monthItemStateChanged
        if (combo_month.getSelectedIndex() != 0) {
            t_sno1.setEnabled(true);
            t_snic1.setEnabled(true);
        } else if (combo_month.getSelectedIndex() == 0) {
            t_sno1.setEnabled(false);
            t_snic1.setEnabled(false);
        }
    }//GEN-LAST:event_combo_monthItemStateChanged

    void resetFields() {
        t_sno1.setText("");
        t_snic1.setText("");
        t_sname1.setText("");
        t_due.setText("0.00");
        t_fee.setText("0.00");
        l_totalfee.setText("0");
        l_totalfeecents.setText(".00");
        combo_month.setSelectedIndex(0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bfinish;
    private javax.swing.JComboBox combo_month;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel l_totalfee;
    private javax.swing.JLabel l_totalfeecents;
    private javax.swing.JLabel labelDue;
    private javax.swing.JLayeredPane layer_payment;
    private javax.swing.JTextField t_due;
    private javax.swing.JTextField t_fee;
    private javax.swing.JTextField t_sname1;
    private javax.swing.JTextField t_snic1;
    private javax.swing.JTextField t_sno1;
    // End of variables declaration//GEN-END:variables
}
