/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package london;

import Connection.jdbc;
import jBCrypt.BCrypt;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joshua
 */
public class user_manage extends javax.swing.JFrame {

    newHome h = null;

    public user_manage() {

        initComponents();
        loadtable();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t_name = new javax.swing.JTextField();
        t_uname = new javax.swing.JTextField();
        t_pass = new javax.swing.JPasswordField();
        t_pass2 = new javax.swing.JPasswordField();
        bcreate = new javax.swing.JButton();
        bdelete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("User Management--Encrypted Procedure");
        setAlwaysOnTop(true);
        setType(java.awt.Window.Type.UTILITY);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("User Accounts");
        jLabel5.setBounds(10, 10, 310, 50);
        jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Name", "Username", "Password"
            }
        ));
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jScrollPane1.setBounds(10, 130, 560, 110);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setText("Only the Adminstrator or the owner is allowed here");
        jLabel1.setBounds(10, 50, 320, 14);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Username");
        jLabel2.setBounds(50, 280, 70, 14);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Password");
        jLabel3.setBounds(50, 310, 70, 14);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Confirm password");
        jLabel4.setBounds(10, 340, 110, 14);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        t_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_nameFocusLost(evt);
            }
        });
        t_name.setBounds(130, 250, 200, 24);
        jLayeredPane1.add(t_name, javax.swing.JLayeredPane.DEFAULT_LAYER);

        t_uname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_uname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_unameFocusLost(evt);
            }
        });
        t_uname.setBounds(130, 280, 200, 24);
        jLayeredPane1.add(t_uname, javax.swing.JLayeredPane.DEFAULT_LAYER);

        t_pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_passFocusLost(evt);
            }
        });
        t_pass.setBounds(130, 310, 200, 24);
        jLayeredPane1.add(t_pass, javax.swing.JLayeredPane.DEFAULT_LAYER);

        t_pass2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_pass2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_pass2FocusLost(evt);
            }
        });
        t_pass2.setBounds(130, 340, 200, 24);
        jLayeredPane1.add(t_pass2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bcreate.setText("create user");
        bcreate.setOpaque(false);
        bcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcreateActionPerformed(evt);
            }
        });
        bcreate.setBounds(370, 250, 170, 50);
        jLayeredPane1.add(bcreate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bdelete.setText("delete");
        bdelete.setOpaque(false);
        bdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeleteActionPerformed(evt);
            }
        });
        bdelete.setBounds(370, 310, 170, 50);
        jLayeredPane1.add(bdelete, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setDisplayedMnemonic('x');
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img$icon/log1.png"))); // NOI18N
        jLabel6.setText("exit");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jLabel6.setBounds(490, 0, 80, 18);
        jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Name");
        jLabel7.setBounds(50, 250, 70, 14);
        jLayeredPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel32.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img$icon/LB4.png"))); // NOI18N
        jLabel32.setEnabled(false);
        jLabel32.setBounds(-260, 0, 840, 550);
        jLayeredPane1.add(jLabel32, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 579, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 368, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 368, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );

        setBounds(690, 400, 595, 404);
    }// </editor-fold>//GEN-END:initComponents

    private void bcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcreateActionPerformed
        loadtable();
        //------------------------
        //-------NEW*update on 2013-02-09@11.15PM below
        //------- setting pass with a crypted pass
        String hashed = BCrypt.hashpw(new String(t_pass2.getPassword()), BCrypt.gensalt());
        //------------------old written procedure continues...........
        try {
            if (new String(t_pass.getPassword()).equals(new String(t_pass2.getPassword()))) {
                jdbc.con().createStatement().executeUpdate("insert into users(name,username,password)"
                        + " values('" + t_name.getText() + "','" + t_uname.getText() + "','"
                        + hashed + "') ");
            } else {
                JOptionPane.showMessageDialog(null, "Passwords do not match \n Try again !", "Error", 2);
            }
            t_name.setText("");
            t_uname.setText("");
            t_pass.setText("");
            t_pass2.setText("");
        } catch (Exception e) {
            System.out.println(e);
        }
        this.dispose();
        new user_manage().setVisible(true);

    }//GEN-LAST:event_bcreateActionPerformed

    private void bdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeleteActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        Statement st = null;
        int sRow = jTable1.getSelectedRow();
        if (sRow == 0) {
            JOptionPane.showMessageDialog(null, "You cannot delete the Administrator account", "Error", 2);
        } else {
            try {
                //jdbc.con().createStatement().executeUpdate("delete from users where uid='" + dtm.getValueAt(sRow, 0) + "'");
                st = jdbc.con().createStatement();
                st.executeUpdate("delete from users where uid='" + dtm.getValueAt(sRow, 0) + "'");

                dtm.removeRow(jTable1.getSelectedRow());
            } catch (Exception ex) {
                System.out.println("delete error in users table");
                System.out.println(ex);
            } finally {
                try {
                    if (st != null) {
                        st.close();
                    }
                } catch (SQLException e) {
                    System.out.println(e);
                }
            }
        }
        this.dispose();
        new user_manage().setVisible(true);

    }//GEN-LAST:event_bdeleteActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        JOptionPane.showMessageDialog(null, "Invalid Function \n Keyboard Operation is not allowed!", "Error", 2);
    }//GEN-LAST:event_jTable1KeyPressed

    private void t_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_nameFocusLost
        t_uname.grabFocus();
    }//GEN-LAST:event_t_nameFocusLost

    private void t_unameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_unameFocusLost
        t_pass.grabFocus();
    }//GEN-LAST:event_t_unameFocusLost

    private void t_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_passFocusLost
        t_pass2.grabFocus();
    }//GEN-LAST:event_t_passFocusLost

    private void t_pass2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_pass2FocusLost
        bcreate.grabFocus();
    }//GEN-LAST:event_t_pass2FocusLost

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.dispose();
        /*
         * h = new newHome();
         * h.setState(newHome.NORMAL);
         * above stuff are deprecated !!! use JVMTI to access objects in JVM
         *
         */
    }//GEN-LAST:event_jLabel6MouseClicked

    final void loadtable() {
        ResultSet rs = null;
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        try {
            rs = jdbc.con().createStatement().executeQuery("select * from users");
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("uid"));
                v.add(rs.getString("name"));
                v.add(rs.getString("username"));
                v.add(rs.getString("password"));
                dtm.addRow(v);
            }
            JOptionPane.showMessageDialog(null, "Database successfully Synced to table");
        } catch (Exception ex) {
            System.out.println("Error loading users table");
            System.out.println(ex);
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
            } catch (SQLException e) {
                System.out.println(e);
            }
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    UIManager.setLookAndFeel(new NimbusLookAndFeel());
                    new user_manage().setVisible(true);
                } catch (UnsupportedLookAndFeelException ex) {
                    System.out.println(ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcreate;
    private javax.swing.JButton bdelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField t_name;
    private javax.swing.JPasswordField t_pass;
    private javax.swing.JPasswordField t_pass2;
    private javax.swing.JTextField t_uname;
    // End of variables declaration//GEN-END:variables
}
